-- Codes are generated by BEFORE INSERT triggers. A missing one surfaces as a
-- not-null violation on the code column, which is how campaign creation failed.
\set ON_ERROR_STOP on

CREATE OR REPLACE FUNCTION pg_temp.expect(p_ok boolean, p_what text) RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
  IF NOT p_ok THEN RAISE EXCEPTION 'FAILED: %', p_what; END IF;
  RAISE NOTICE '  ok  %', p_what;
END $$;

BEGIN;
\i supabase/tests/10_fixtures.sql

-- Every table that generates its own code must carry the trigger.
SELECT pg_temp.expect(
  (SELECT count(*) FROM pg_trigger
    WHERE NOT tgisinternal
      AND tgname IN ('set_farmer_code','set_order_code','set_campaign_code','set_vehicle_code',
                     'set_driver_code','set_manifest_code','set_pod_code','set_recon_code')) = 8,
  'all eight code-generation triggers exist');

-- Creating a campaign the way the API does it: no campaign_code supplied.
INSERT INTO campaigns(name, season, district_id, value_chain_id, distribution_site_id,
                      source_warehouse_id, start_date, end_date, status, created_by)
VALUES ('Trigger Test', '2026 Test', 901, 901, 901, 901,
        now(), now() + interval '30 days', 'Draft', 901);
SELECT pg_temp.expect(
  (SELECT campaign_code FROM campaigns WHERE name = 'Trigger Test') LIKE 'CAM-%',
  'a campaign created without a code is given one');

INSERT INTO vehicles(plate_number, vehicle_type) VALUES ('TRG-001', 'Truck');
SELECT pg_temp.expect(
  (SELECT vehicle_code FROM vehicles WHERE plate_number = 'TRG-001') LIKE 'VEH-%',
  'a vehicle created without a code is given one');

INSERT INTO drivers(full_name) VALUES ('Trigger Driver');
SELECT pg_temp.expect(
  (SELECT driver_code FROM drivers WHERE full_name = 'Trigger Driver') LIKE 'DRV-%',
  'a driver created without a code is given one');
ROLLBACK;

-- ── The failure, and the repair ──────────────────────────────────────────────
BEGIN;
\i supabase/tests/10_fixtures.sql
-- Production has neither the trigger nor the column default that schema.sql
-- declares, so the insert arrives with a literal NULL. Reproduce both.
DROP TRIGGER IF EXISTS set_campaign_code ON campaigns;
ALTER TABLE campaigns ALTER COLUMN campaign_code DROP DEFAULT;

DO $$ BEGIN
  INSERT INTO campaigns(name, season, district_id, value_chain_id, distribution_site_id,
                        source_warehouse_id, start_date, end_date, status)
  VALUES ('No Trigger', '2026 Test', 901, 901, 901, 901,
          now(), now() + interval '30 days', 'Draft');
  RAISE EXCEPTION 'FAILED: a campaign was created with no code trigger, so this proves nothing';
EXCEPTION WHEN not_null_violation THEN
  RAISE NOTICE '  ok  without the trigger a campaign hits the not-null violation the user saw';
END $$;

\i supabase/migrations/20260907030000_restore_code_generation_triggers.sql

INSERT INTO campaigns(name, season, district_id, value_chain_id, distribution_site_id,
                      source_warehouse_id, start_date, end_date, status)
VALUES ('Repaired', '2026 Test', 901, 901, 901, 901,
        now(), now() + interval '30 days', 'Draft');
SELECT pg_temp.expect(
  (SELECT campaign_code FROM campaigns WHERE name = 'Repaired') LIKE 'CAM-%',
  'replaying the migration restores the trigger and the insert succeeds');
ROLLBACK;
