-- Add chiefdoms for all Sierra Leone districts.
-- Uses INSERT ... ON CONFLICT DO NOTHING so existing rows are preserved.
-- Run once against the live database.

INSERT INTO chiefdoms (name, district_id)
SELECT c.name, d.id
FROM (VALUES
  -- Bo (13)
  ('Bagbwe',        'Bo'),
  ('Badjia',        'Bo'),
  ('Boama',         'Bo'),
  ('Bumpe Ngao',    'Bo'),
  ('Gbo',           'Bo'),
  ('Jaiama Bongor', 'Bo'),
  ('Kakua',         'Bo'),
  ('Komboya',       'Bo'),
  ('Lugbu',         'Bo'),
  ('Niawa Lenga',   'Bo'),
  ('Selenga',       'Bo'),
  ('Tikonko',       'Bo'),
  ('Wunde',         'Bo'),
  -- Bombali (12)
  ('Biriwa',               'Bombali'),
  ('Bombali Shebora',      'Bombali'),
  ('Bombali Simiria',      'Bombali'),
  ('Gbanti Kamaranka',     'Bombali'),
  ('Gbendembu Ngowahun',   'Bombali'),
  ('Libeisaygahun',        'Bombali'),
  ('Magbaimba Ndowahun',   'Bombali'),
  ('Makari Gbanti',        'Bombali'),
  ('Ngowahun',             'Bombali'),
  ('Paki Masabong',        'Bombali'),
  ('Sanda Loko',           'Bombali'),
  ('Safroko Limba',        'Bombali'),
  -- Bonthe (11)
  ('Banta Mokele',   'Bonthe'),
  ('Dema',           'Bonthe'),
  ('Fakunya',        'Bonthe'),
  ('Jong',           'Bonthe'),
  ('Kpanda Kemoh',   'Bonthe'),
  ('Kwamebai Krim',  'Bonthe'),
  ('Nongoba Bullom', 'Bonthe'),
  ('Ribbi',          'Bonthe'),
  ('Sogbeni',        'Bonthe'),
  ('Sittia',         'Bonthe'),
  ('Yawbeko',        'Bonthe'),
  -- Kailahun (14)
  ('Dea',          'Kailahun'),
  ('Fiama',        'Kailahun'),
  ('Gaura',        'Kailahun'),
  ('Jawie',        'Kailahun'),
  ('Kissi Kama',   'Kailahun'),
  ('Kissi Teng',   'Kailahun'),
  ('Kissi Tongi',  'Kailahun'),
  ('Kpeje Bongre', 'Kailahun'),
  ('Kpeje West',   'Kailahun'),
  ('Luawa',        'Kailahun'),
  ('Malema',       'Kailahun'),
  ('Mandu',        'Kailahun'),
  ('Njaluahun',    'Kailahun'),
  ('Penguia',      'Kailahun'),
  -- Kambia (6)
  ('Bramaia',       'Kambia'),
  ('Gbinle Dixing', 'Kambia'),
  ('Magbema',       'Kambia'),
  ('Mambolo',       'Kambia'),
  ('Samu',          'Kambia'),
  ('Tonko Limba',   'Kambia'),
  -- Kenema (15)
  ('Dama',           'Kenema'),
  ('Dodo',           'Kenema'),
  ('Gorama Mende',   'Kenema'),
  ('Kandu Leppiama', 'Kenema'),
  ('Langrama',       'Kenema'),
  ('Lower Bambara',  'Kenema'),
  ('Malegohun',      'Kenema'),
  ('Niawa',          'Kenema'),
  ('Nomo',           'Kenema'),
  ('Nongowa',        'Kenema'),
  ('Simbaru',        'Kenema'),
  ('Small Bo',       'Kenema'),
  ('Tunkia',         'Kenema'),
  ('Wandor',         'Kenema'),
  ('Nomo Kpaa',      'Kenema'),
  -- Koinadugu (11)
  ('Dembelia Sinkunia', 'Koinadugu'),
  ('Falaba',            'Koinadugu'),
  ('Firia',             'Koinadugu'),
  ('Gberia Timberi',    'Koinadugu'),
  ('Kasunko',           'Koinadugu'),
  ('Mongo',             'Koinadugu'),
  ('Neya',              'Koinadugu'),
  ('Nieni',             'Koinadugu'),
  ('Sengbe',            'Koinadugu'),
  ('Sulima',            'Koinadugu'),
  ('Wara Wara Bafodia', 'Koinadugu'),
  -- Kono (14)
  ('Gbane',        'Kono'),
  ('Gbane Kandor', 'Kono'),
  ('Gbense',       'Kono'),
  ('Gorama Kono',  'Kono'),
  ('Kamara',       'Kono'),
  ('Lei',          'Kono'),
  ('Mafindor',     'Kono'),
  ('Nimikoro',     'Kono'),
  ('Nimiyama',     'Kono'),
  ('Sandor',       'Kono'),
  ('Soa',          'Kono'),
  ('Tankoro',      'Kono'),
  ('Toli',         'Kono'),
  ('Yone',         'Kono'),
  -- Moyamba (14)
  ('Bagruwa',      'Moyamba'),
  ('Banta Mokele', 'Moyamba'),
  ('Bumpe',        'Moyamba'),
  ('Dasse',        'Moyamba'),
  ('Fakunya',      'Moyamba'),
  ('Kagboro',      'Moyamba'),
  ('Kaiyamba',     'Moyamba'),
  ('Kargboro',     'Moyamba'),
  ('Kongbora',     'Moyamba'),
  ('Ribbi',        'Moyamba'),
  ('Sittia',       'Moyamba'),
  ('Timdale',      'Moyamba'),
  ('TM Simbaru',   'Moyamba'),
  ('Valunia',      'Moyamba'),
  -- Port Loko (12)
  ('Bureh Kasseh Maconteh', 'Port Loko'),
  ('Dibia',                  'Port Loko'),
  ('Kafe Simira',            'Port Loko'),
  ('Kaffu Bullom',           'Port Loko'),
  ('Lokomasama',             'Port Loko'),
  ('Maforki',                'Port Loko'),
  ('Marampa',                'Port Loko'),
  ('Masimera',               'Port Loko'),
  ('Sanda Magbolontor',      'Port Loko'),
  ('Sanda Tendaren',         'Port Loko'),
  ('Sella Limba',            'Port Loko'),
  ('Tinpot',                 'Port Loko'),
  -- Pujehun (12)
  ('Barri',         'Pujehun'),
  ('Gallinas Perri', 'Pujehun'),
  ('Kpaka',         'Pujehun'),
  ('Malen',         'Pujehun'),
  ('Makpele',       'Pujehun'),
  ('Mano Sakrim',   'Pujehun'),
  ('Panga Kabonde', 'Pujehun'),
  ('Panga Krim',    'Pujehun'),
  ('Penguia',       'Pujehun'),
  ('Soro Gbema',    'Pujehun'),
  ('Valunia',       'Pujehun'),
  ('Yakaju',        'Pujehun'),
  -- Tonkolili (11)
  ('Gbonkolenken',    'Tonkolili'),
  ('Kalansogoia',     'Tonkolili'),
  ('Kholifa Mabang',  'Tonkolili'),
  ('Kholifa Rowalla', 'Tonkolili'),
  ('Kunike',          'Tonkolili'),
  ('Kunike Barina',   'Tonkolili'),
  ('Malal Mara',      'Tonkolili'),
  ('Sambaia Bendugu', 'Tonkolili'),
  ('Tane',            'Tonkolili'),
  ('Yoni',            'Tonkolili'),
  ('Yoni Bana',       'Tonkolili'),
  -- Western Area Rural (5)
  ('Waterloo Rural',   'Western Area Rural'),
  ('Lumley Rural',     'Western Area Rural'),
  ('Gloucester Rural', 'Western Area Rural'),
  ('Mountain Rural',   'Western Area Rural'),
  ('Goderich Rural',   'Western Area Rural'),
  -- Western Area Urban (3)
  ('Central Freetown', 'Western Area Urban'),
  ('East End',         'Western Area Urban'),
  ('West End',         'Western Area Urban')
) AS c(name, district_name)
JOIN districts d ON d.name = c.district_name
ON CONFLICT DO NOTHING;
