-- Offline-first delivery verification for low-connectivity field operations.
-- Evidence is captured on-device and reconciled by the API when connectivity returns.

BEGIN;

ALTER TABLE public.pod_verification_proofs
  ADD COLUMN IF NOT EXISTS method text,
  ADD COLUMN IF NOT EXISTS issued_by integer REFERENCES public.users(id),
  ADD COLUMN IF NOT EXISTS issued_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS revoked_at timestamptz,
  ADD COLUMN IF NOT EXISTS attempt_count integer NOT NULL DEFAULT 0;

UPDATE public.pod_verification_proofs
SET method = CASE WHEN kind = 'face' THEN 'face' ELSE 'online_otp' END
WHERE method IS NULL;

ALTER TABLE public.pod_verification_proofs
  ALTER COLUMN method SET NOT NULL,
  ALTER COLUMN method SET DEFAULT 'online_otp';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pod_verification_proofs_method_check'
      AND conrelid = 'public.pod_verification_proofs'::regclass
  ) THEN
    ALTER TABLE public.pod_verification_proofs
      ADD CONSTRAINT pod_verification_proofs_method_check
      CHECK (method IN ('online_otp', 'offline_qr', 'offline_pin', 'face'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS pod_verification_proofs_dispatch_method_idx
  ON public.pod_verification_proofs (dispatch_id, farmer_id, method, expires_at DESC);
CREATE INDEX IF NOT EXISTS pod_verification_proofs_farmer_idx
  ON public.pod_verification_proofs (farmer_id);
CREATE INDEX IF NOT EXISTS pod_verification_proofs_issued_by_idx
  ON public.pod_verification_proofs (issued_by) WHERE issued_by IS NOT NULL;

-- This internal proof table is API-only. RLS is enabled as defense in depth;
-- no browser policy is intentional because service_role performs all access.
ALTER TABLE public.pod_verification_proofs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.pod_verification_proofs FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.pod_verification_proofs TO service_role;

CREATE OR REPLACE FUNCTION public.issue_offline_verification_proofs(
  p_dispatch_id integer,
  p_issued_by integer,
  p_proofs jsonb
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count integer;
BEGIN
  IF jsonb_typeof(p_proofs) IS DISTINCT FROM 'array' OR jsonb_array_length(p_proofs) = 0 THEN
    RAISE EXCEPTION 'offline proofs must be a non-empty array' USING ERRCODE = '22023';
  END IF;
  PERFORM 1 FROM public.dispatches WHERE id = p_dispatch_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'dispatch % does not exist', p_dispatch_id USING ERRCODE = '23503';
  END IF;

  UPDATE public.pod_verification_proofs
  SET revoked_at = now()
  WHERE dispatch_id = p_dispatch_id
    AND method IN ('offline_qr', 'offline_pin')
    AND consumed_at IS NULL
    AND revoked_at IS NULL;

  INSERT INTO public.pod_verification_proofs
    (token_hash, kind, method, farmer_id, dispatch_id, status, expires_at, issued_by)
  SELECT token_hash, 'otp', method, farmer_id, p_dispatch_id, 'Verified', expires_at, p_issued_by
  FROM jsonb_to_recordset(p_proofs) AS proof(
    token_hash text,
    method text,
    farmer_id integer,
    expires_at timestamptz
  )
  WHERE token_hash IS NOT NULL
    AND method IN ('offline_qr', 'offline_pin')
    AND farmer_id IS NOT NULL
    AND expires_at > now();
  GET DIAGNOSTICS v_count = ROW_COUNT;
  IF v_count <> jsonb_array_length(p_proofs) THEN
    RAISE EXCEPTION 'one or more offline proofs are invalid' USING ERRCODE = '22023';
  END IF;
  RETURN v_count;
END $$;

REVOKE ALL ON FUNCTION public.issue_offline_verification_proofs(integer, integer, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.issue_offline_verification_proofs(integer, integer, jsonb)
  TO service_role;

CREATE TABLE IF NOT EXISTS public.dispatch_arrival_evidence (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evidence_key          text NOT NULL UNIQUE,
  dispatch_id           integer NOT NULL REFERENCES public.dispatches(id),
  vehicle_id            integer REFERENCES public.vehicles(id),
  source                text NOT NULL DEFAULT 'mobile_gnss'
    CHECK (source IN ('mobile_gnss', 'hardware_tracker', 'reconciled', 'manual_exception')),
  verification_status   text NOT NULL DEFAULT 'Pending Synchronisation'
    CHECK (verification_status IN (
      'Pending Synchronisation', 'GPS Verified', 'Needs Review', 'Rejected', 'Manual Exception'
    )),
  destination_latitude  double precision NOT NULL CHECK (destination_latitude BETWEEN -90 AND 90),
  destination_longitude double precision NOT NULL CHECK (destination_longitude BETWEEN -180 AND 180),
  geofence_radius_m     integer NOT NULL CHECK (geofence_radius_m BETWEEN 50 AND 20000),
  fixes                 jsonb NOT NULL CHECK (jsonb_typeof(fixes) = 'array'),
  fix_count             integer NOT NULL CHECK (fix_count >= 1),
  acceptable_fix_count  integer NOT NULL CHECK (acceptable_fix_count BETWEEN 0 AND fix_count),
  first_captured_at     timestamptz NOT NULL,
  last_captured_at      timestamptz NOT NULL,
  dwell_seconds         integer NOT NULL DEFAULT 0 CHECK (dwell_seconds >= 0),
  minimum_distance_m    integer CHECK (minimum_distance_m IS NULL OR minimum_distance_m >= 0),
  best_accuracy_m       double precision CHECK (best_accuracy_m IS NULL OR best_accuracy_m >= 0),
  device_id             text,
  exception_reason      text,
  captured_by           integer REFERENCES public.users(id),
  reviewed_by           integer REFERENCES public.users(id),
  reviewed_at           timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CHECK (last_captured_at >= first_captured_at),
  CHECK (source <> 'manual_exception' OR nullif(btrim(exception_reason), '') IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS dispatch_arrival_evidence_dispatch_idx
  ON public.dispatch_arrival_evidence (dispatch_id, last_captured_at DESC);
CREATE INDEX IF NOT EXISTS dispatch_arrival_evidence_vehicle_idx
  ON public.dispatch_arrival_evidence (vehicle_id, last_captured_at DESC)
  WHERE vehicle_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS dispatch_arrival_evidence_captured_by_idx
  ON public.dispatch_arrival_evidence (captured_by) WHERE captured_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS dispatch_arrival_evidence_reviewed_by_idx
  ON public.dispatch_arrival_evidence (reviewed_by) WHERE reviewed_by IS NOT NULL;

ALTER TABLE public.dispatch_arrival_evidence ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS dispatch_arrival_management_read ON public.dispatch_arrival_evidence;
CREATE POLICY dispatch_arrival_management_read ON public.dispatch_arrival_evidence
FOR SELECT TO authenticated
USING (private.invendis_has_role(ARRAY['admin','projectmanager','warehousemanager','districtcoordinator']));

REVOKE ALL ON public.dispatch_arrival_evidence FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.dispatch_arrival_evidence TO authenticated;
GRANT ALL ON public.dispatch_arrival_evidence TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.dispatch_arrival_evidence_id_seq TO service_role;

ALTER TABLE public.pod
  ADD COLUMN IF NOT EXISTS beneficiary_verification_method text NOT NULL DEFAULT 'online_otp',
  ADD COLUMN IF NOT EXISTS sync_verification_status text NOT NULL DEFAULT 'Pending Verification',
  ADD COLUMN IF NOT EXISTS gps_captured_at timestamptz,
  ADD COLUMN IF NOT EXISTS arrival_evidence_id bigint REFERENCES public.dispatch_arrival_evidence(id);

UPDATE public.pod
SET beneficiary_verification_method = CASE
      WHEN otp_status = 'Verified' THEN 'online_otp'
      ELSE 'supervisor_exception'
    END,
    sync_verification_status = CASE
      WHEN status = 'Verified' AND otp_status = 'Verified' THEN 'Verified Online'
      WHEN status = 'Rejected' THEN 'Rejected'
      WHEN status = 'Exception' OR otp_status IS DISTINCT FROM 'Verified' THEN 'Needs Review'
      ELSE 'Pending Verification'
    END;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pod_beneficiary_verification_method_check'
      AND conrelid = 'public.pod'::regclass
  ) THEN
    ALTER TABLE public.pod ADD CONSTRAINT pod_beneficiary_verification_method_check
      CHECK (beneficiary_verification_method IN ('online_otp', 'offline_qr', 'offline_pin', 'supervisor_exception'));
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pod_sync_verification_status_check'
      AND conrelid = 'public.pod'::regclass
  ) THEN
    ALTER TABLE public.pod ADD CONSTRAINT pod_sync_verification_status_check
      CHECK (sync_verification_status IN ('Verified Online', 'Pending Verification', 'Verified After Sync', 'Needs Review', 'Rejected'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS pod_arrival_evidence_idx
  ON public.pod (arrival_evidence_id);

DROP TRIGGER IF EXISTS audit_dispatch_arrival_evidence_business_change
  ON public.dispatch_arrival_evidence;
CREATE TRIGGER audit_dispatch_arrival_evidence_business_change
AFTER INSERT OR UPDATE OR DELETE ON public.dispatch_arrival_evidence
FOR EACH ROW EXECUTE FUNCTION private.audit_business_change();

COMMIT;
