-- Phase 1: curated AVDP road register and GPS survey sessions.
-- Raw tracker points remain immutable in gps_track; surveys reference a bounded
-- vehicle/time window and store only reproducible processing metrics.

BEGIN;

CREATE TABLE IF NOT EXISTS public.roads (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  road_code           text NOT NULL UNIQUE,
  name                text NOT NULL,
  district_id         integer NOT NULL REFERENCES public.districts(id),
  start_location      text NOT NULL,
  end_location        text NOT NULL,
  intervention_type   text NOT NULL DEFAULT 'Existing Feeder Road'
    CHECK (intervention_type IN (
      'AVDP Feeder Road', 'AVDP Access Road', 'Existing Feeder Road', 'Other'
    )),
  surface_type        text NOT NULL DEFAULT 'Unknown'
    CHECK (surface_type IN ('Earth', 'Gravel', 'Paved', 'Mixed', 'Unknown')),
  project_status      text NOT NULL DEFAULT 'Planned'
    CHECK (project_status IN (
      'Planned', 'Under Construction', 'Completed', 'Operational', 'Suspended'
    )),
  planned_length_km   numeric(10,3)
    CHECK (planned_length_km IS NULL OR planned_length_km > 0),
  contractor_name     text,
  contract_reference  text,
  planned_start_date  date,
  planned_end_date    date,
  notes               text,
  is_active           boolean NOT NULL DEFAULT true,
  created_by          integer REFERENCES public.users(id),
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CHECK (planned_end_date IS NULL OR planned_start_date IS NULL OR planned_end_date >= planned_start_date),
  CHECK (btrim(name) <> '' AND btrim(start_location) <> '' AND btrim(end_location) <> '')
);

CREATE TABLE IF NOT EXISTS public.road_surveys (
  id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_code              text NOT NULL UNIQUE,
  road_id                  bigint NOT NULL REFERENCES public.roads(id),
  vehicle_id               integer REFERENCES public.vehicles(id),
  source_type              text NOT NULL DEFAULT 'vehicle_tracker'
    CHECK (source_type IN ('vehicle_tracker', 'handheld_gps', 'mobile_gps')),
  purpose                  text NOT NULL DEFAULT 'baseline'
    CHECK (purpose IN ('baseline', 'construction_progress', 'completion', 'inspection', 'accessibility')),
  status                   text NOT NULL DEFAULT 'Draft'
    CHECK (status IN ('Draft', 'Ready for Review', 'Approved', 'Rejected')),
  started_at               timestamptz NOT NULL,
  ended_at                 timestamptz NOT NULL,
  surveyor_name            text NOT NULL,
  surveyed_length_km       numeric(12,3),
  raw_point_count          integer NOT NULL DEFAULT 0 CHECK (raw_point_count >= 0),
  accepted_point_count     integer NOT NULL DEFAULT 0 CHECK (accepted_point_count >= 0),
  discarded_point_count    integer NOT NULL DEFAULT 0 CHECK (discarded_point_count >= 0),
  segment_count            integer NOT NULL DEFAULT 0 CHECK (segment_count >= 0),
  gap_count                integer NOT NULL DEFAULT 0 CHECK (gap_count >= 0),
  average_speed_kmh        numeric(8,2),
  quality_status           text NOT NULL DEFAULT 'Not processed'
    CHECK (quality_status IN ('Not processed', 'Good', 'Needs Review', 'Insufficient')),
  processing_notes         text,
  field_notes              text,
  rejection_reason         text,
  processed_at             timestamptz,
  reviewed_by              integer REFERENCES public.users(id),
  reviewed_at              timestamptz,
  created_by               integer REFERENCES public.users(id),
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  CHECK (ended_at > started_at),
  CHECK (ended_at <= started_at + interval '72 hours'),
  CHECK (source_type <> 'vehicle_tracker' OR vehicle_id IS NOT NULL),
  CHECK (status <> 'Approved' OR (processed_at IS NOT NULL AND accepted_point_count >= 2)),
  CHECK (status <> 'Rejected' OR nullif(btrim(rejection_reason), '') IS NOT NULL),
  CHECK (btrim(surveyor_name) <> '')
);

CREATE TABLE IF NOT EXISTS public.road_survey_observations (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survey_id         bigint NOT NULL REFERENCES public.road_surveys(id) ON DELETE CASCADE,
  observation_type  text NOT NULL
    CHECK (observation_type IN (
      'Bridge', 'Culvert', 'Pothole', 'Washout', 'Flooding',
      'Community', 'Market', 'Construction', 'Other'
    )),
  severity          text CHECK (severity IS NULL OR severity IN ('Low', 'Medium', 'High', 'Critical')),
  latitude          double precision NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude         double precision NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  chainage_km       numeric(10,3) CHECK (chainage_km IS NULL OR chainage_km >= 0),
  notes             text,
  photo_url         text,
  captured_at       timestamptz NOT NULL DEFAULT now(),
  created_by        integer REFERENCES public.users(id),
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS roads_district_status_idx
  ON public.roads (district_id, project_status) WHERE is_active;
CREATE INDEX IF NOT EXISTS road_surveys_road_started_idx
  ON public.road_surveys (road_id, started_at DESC);
CREATE INDEX IF NOT EXISTS road_surveys_vehicle_window_idx
  ON public.road_surveys (vehicle_id, started_at, ended_at)
  WHERE vehicle_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS road_surveys_status_started_idx
  ON public.road_surveys (status, started_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS road_surveys_unique_tracker_window_idx
  ON public.road_surveys (road_id, vehicle_id, started_at, ended_at)
  WHERE vehicle_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS road_survey_observations_survey_idx
  ON public.road_survey_observations (survey_id, captured_at);

ALTER TABLE public.roads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.road_surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.road_survey_observations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS road_management_read ON public.roads;
CREATE POLICY road_management_read ON public.roads
FOR SELECT TO authenticated
USING (private.invendis_has_role(ARRAY['admin','projectmanager','warehousemanager']));

DROP POLICY IF EXISTS road_survey_management_read ON public.road_surveys;
CREATE POLICY road_survey_management_read ON public.road_surveys
FOR SELECT TO authenticated
USING (private.invendis_has_role(ARRAY['admin','projectmanager','warehousemanager']));

DROP POLICY IF EXISTS road_observation_management_read ON public.road_survey_observations;
CREATE POLICY road_observation_management_read ON public.road_survey_observations
FOR SELECT TO authenticated
USING (private.invendis_has_role(ARRAY['admin','projectmanager','warehousemanager']));

-- Browser clients may read management data but all mutations pass through the
-- authenticated application API. Explicit service-role grants also accommodate
-- Supabase's 2026 Data API auto-exposure change for newly-created tables.
REVOKE ALL ON public.roads, public.road_surveys, public.road_survey_observations
  FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.roads, public.road_surveys, public.road_survey_observations
  TO authenticated;
GRANT ALL ON public.roads, public.road_surveys, public.road_survey_observations
  TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.roads_id_seq,
  public.road_surveys_id_seq, public.road_survey_observations_id_seq
  TO service_role;

DROP TRIGGER IF EXISTS audit_roads_business_change ON public.roads;
CREATE TRIGGER audit_roads_business_change
AFTER INSERT OR UPDATE OR DELETE ON public.roads
FOR EACH ROW EXECUTE FUNCTION private.audit_business_change();

DROP TRIGGER IF EXISTS audit_road_surveys_business_change ON public.road_surveys;
CREATE TRIGGER audit_road_surveys_business_change
AFTER INSERT OR UPDATE OR DELETE ON public.road_surveys
FOR EACH ROW EXECUTE FUNCTION private.audit_business_change();

DROP TRIGGER IF EXISTS audit_road_observations_business_change ON public.road_survey_observations;
CREATE TRIGGER audit_road_observations_business_change
AFTER INSERT OR UPDATE OR DELETE ON public.road_survey_observations
FOR EACH ROW EXECUTE FUNCTION private.audit_business_change();

COMMIT;
